Increment 3
sergalkin/go-url-shortener pull request #3
Opened 2022-03-20 23:10 UTC by sergalkin

feat: Added chi router

2022-03-22 15:48 UTC, lugingf requested changes
Можешь сбросить ветку main, так чтобы в одном PR были видны все изменения по всем инкрементам текущего спринта?

2022-03-22 16:43 UTC, sergalkin commented
Сбросил. Я подумал, что нужно мерджить предыдущие инкременты, а не просто от них создавать все последующие ветки

2022-03-22 19:46 UTC, lugingf commented
> Сбросил. Я подумал, что нужно мерджить предыдущие инкременты, а не просто от них создавать все последующие ветки

Не, как только ментор аппрувит ПР - тогда все разом и мержим

2022-03-22 19:51 UTC, lugingf requested changes
В общем все очень нравится. Оставил комментарий, давай поправим

2022-03-22 19:51 UTC, lugingf commented on internal/app/interfaces/expand.go
> +package interfaces
Ну, я если честно против такого выделения "Интерфейсы" в отдельный пакет)
Обычно интерфейс объявляется в том пакете, который его реализует.

2022-03-22 20:00 UTC, sergalkin commented on internal/app/interfaces/expand.go
> +package interfaces
Окей тогда несколько вопросов:
1. У меня есть интерфейс URLShorten, я его должен поместить в пакет с хэндлерами. Но вот нужно ли его отдельно создавать как url-shorten.go или же я его просто кладу в shorten.go и это считается нормально?
2.  Если я их храню отдельно, нужно ли их тогда как-то помечать, например: мой нынешний interfaces/storage.go переедет в папку storage/storage.go или же storage/storage-interface.go?

2022-03-22 20:04 UTC, lugingf commented on internal/app/interfaces/expand.go
> +package interfaces
>URLShorten, я его должен поместить в пакет с хэндлерами
Вот тут чуть странно, если это интерфейс именно для хендлера, то ладно

>или же я его просто кладу в shorten.go и это считается нормально?
Если он один (два) то нормально

>переедет в папку storage/storage.go или же storage/storage-interface.go?
Если он один и легко находится (или если реализация всего одна) то норм положить вместе. Если оно разрастается, или появляется много реализаций, тогда лучше отдельно положить, чтобы в глаза бросался

2022-03-22 20:28 UTC, sergalkin commented
Еще парочка вопросов относительно ревью:
1. Я же правильно понимаю, что кнопку Resolve conversation жму не я?) 
2. После исправлений, мне нужно заново тыкать в Re request review + на практикуме отправлять заново ссылку?
3. При задавании вопросов внутри conversation, ничего дополнительно тыкать не нужно и просто ждать ответа, так?

2022-03-23 12:09 UTC, lugingf commented
> Еще парочка вопросов относительно ревью:
> 
> 1. Я же правильно понимаю, что кнопку Resolve conversation жму не я?)

На эту кнопку вообще пофиг) Но лучше не жми, а то я по потеряю свои комментарии и буду тупить))

> 2. После исправлений, мне нужно заново тыкать в Re request review + на практикуме отправлять заново ссылку?

Ага, главное на практикуме заново отправить домашку. А перезапрос ревью в гите - чисто дополнительная штука. Я больше реагирую за уведомлялки, которые движок практикума нам шлет

> 3. При задавании вопросов внутри conversation, ничего дополнительно тыкать не нужно и просто ждать ответа, так?

Если ты не переотправлял домашку, а только задал вопросы, то лучше бы в слак пингануть. Хотя нас просят поменьше общения внутри гита, и побольше вопросов в слаке, чтобы другие студенты могли что-нибудь полезное для себя узнать

2022-03-23 12:10 UTC, lugingf approved these changes
Принято, спасибо :)

2022-03-23 13:00 UTC, sergalkin commented
Понял, спасибо :)

2022-03-23 13:00 UTC, merged